base_url: ''
title: "CLC 2017"

defaults:
  - scope: {path: ""}
    values:
      layout: "page"

main_menu:
  - {"url": "/", title: "home"}
  - {"url": "/information.html", title: "information"}
  - {"url": "/board.html", title: "board"}
  - {"url": "/reg-deadlines.html", title: "registration"}
  - {"url": "/authors.html", title: "author's area"}
  - {"url": "/venue.html", title: "venue"}
  - {"url": "/contacts.html", title: "contacts"}
